version: '3.1'
services:
  statistics-server:
    build: statistics/statistics-server
    image: ewm-statistics-server
    container_name: ewm-statistics-server
    ports:
      - "9090:9090"
    depends_on:
      - statistics-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  statistics-db:
    image: postgres:14-alpine
    container_name: statistics-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main:
    build: main
    image: ewm-main
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:

      - SPRING_DATASOURCE_URL_EWM=jdbc:postgresql://ewm-db:5430/ewm-db
      - SPRING_DATASOURCE_USERNAME_EWM=root
      - SPRING_DATASOURCE_PASSWORD_EWM=root

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6540:5430"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
